spring.application.name=findnet
spring.datasource.url=jdbc:h2:file:./data/findnet
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# SendGrid details
spring.sendgrid.api-key=${SENDGRID_API_KEY}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- DEV MODE: print OTP to console instead of emailing (set to true if no SendGrid key)
app.otp.console-mode=false
